name: Build

on:
  push:
    branches: [ '**' ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    # run on ubuntu, windows and macOS
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run cucumber tests
        run: sbt cucumber
